version: '3'
services: 
  tpt-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment: 
      - REACT_APP_MSAL_CLIENT_ID=${REACT_APP_MSAL_CLIENT_ID}
      - REACT_APP_WEB_API_BASE_URI=${REACT_APP_WEB_API_BASE_URI}
      - REACT_APP_MSAL_CLIENT_SCOPE=${REACT_APP_MSAL_CLIENT_SCOPE}
      - REACT_APP_MSAL_TENANT_AUTHORITY_URI=${REACT_APP_MSAL_TENANT_AUTHORITY_URI}
      - REACT_APP_MSAL_CACHE_LOCATION=${REACT_APP_MSAL_CACHE_LOCATION}
      - REACT_APP_MSAL_AUTH_STATE_IN_COOKIE=${REACT_APP_MSAL_AUTH_STATE_IN_COOKIE}
      - REACT_APP_MSAL_LOGIN_REDIRECT_URI=${REACT_APP_MSAL_LOGIN_REDIRECT_URI}
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development