version: '3'
services:
  daikon-app-ce-daikon-app-ce:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=production
